'use client';
import { useEffect, useState } from 'react';

const skills = {
  'Languages & Querying':['SQL','Python · pandas · NumPy','DAX'],
  'Visualization & BI':['Power BI','Excel · PivotTables','XLOOKUP · Macros'],
  'Databases & Tools':['MySQL','MS SQL Server','Jupyter · Git · Tally ERP'],
  'Core Practice':['Data cleaning & validation','Dashboarding & reporting','ETL basics · Stakeholder reporting']
};

export default function Home(){
 const [dark,setDark]=useState(true);
 useEffect(()=>{const s=localStorage.getItem('theme');const d=s?s==='dark':matchMedia('(prefers-color-scheme: dark)').matches;setDark(d);document.documentElement.dataset.theme=d?'dark':'light'},[]);
 const toggle=()=>{const d=!dark;setDark(d);document.documentElement.dataset.theme=d?'dark':'light';localStorage.setItem('theme',d?'dark':'light')};
 return <>
  <a className="skip" href="#main">Skip to content</a>
  <header><a className="logo" href="#top">PM<span>.</span></a><nav aria-label="Primary">{['about','experience','skills','projects','contact'].map(x=><a key={x} href={`#${x}`}>{x}</a>)}</nav><button className="theme" onClick={toggle} aria-label={`Switch to ${dark?'light':'dark'} mode`}>{dark?'☀':'☾'}</button></header>
  <main id="main">
   <section className="hero section" id="top"><div className="hero-copy"><p className="eyebrow"><i/>Available for data opportunities</p><h1>Data that makes the<br/><em>next move clear.</em></h1><p className="lede">I’m Prajesh Makootan, a Data Analyst turning raw data into clear, actionable insight—building dashboards and automations that help teams make faster, evidence-based decisions.</p><div className="actions"><a className="button primary" href="#projects">View my work ↗</a></div></div><aside className="signal"><div className="signal-head"><span>IMPACT SIGNAL</span><b>● LIVE</b></div><div className="bars">{[38,52,47,69,62,81,76,94].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><div className="metric"><strong>Weekly</strong><span>dashboards used by<br/>cross-functional teams</span></div><div className="stats"><span><b>4+</b> Core tools</span><span><b>2</b> Analyst roles</span></div></aside></section>
   <section className="section split" id="about"><div><p className="label">01 / ABOUT</p><h2>Analysis is only useful when people can act on it.</h2></div><div className="about"><p>I’m a Data Analyst with hands-on experience across SQL, Python, and Power BI, currently working as a Business Intelligence Executive at Sarjak Container Lines in Mumbai.</p><p>I enjoy translating messy data and technical findings into recommendations that non-technical stakeholders can actually act on. My background spans an M.C.A. from Mumbai University and a Google Data Analytics Professional Certificate.</p><div className="facts"><span>Based in<br/><b>Vasai, Maharashtra</b></span><span>Currently<br/><b>BI Executive</b></span></div></div></section>
   <section className="section" id="experience"><p className="label">02 / EXPERIENCE</p><h2>Where I’ve made an impact.</h2><div className="timeline"><article><time>JUL 2025 — PRESENT</time><div><p className="company">SARJAK CONTAINER LINES · MUMBAI</p><h3>Executive — Business Intelligence</h3><p>Designed and maintained interactive Power BI dashboards used weekly by cross-functional teams, reducing manual reporting. Partnered with stakeholders to translate business questions into SQL queries and actionable summaries.</p></div></article><article><time>APR — JUN 2025</time><div><p className="company">SKILL UP IT ACADEMY (APTECH) · MUMBAI</p><h3>Data Analyst Trainee — Capstone Project</h3><p>Built an end-to-end analytics project using Power BI, Excel, SQL, and Python—from raw data preparation to a decision-ready dashboard.</p></div></article></div></section>
   <section className="section" id="skills"><p className="label">03 / TOOLKIT</p><h2>The right tool for the question.</h2><div className="skills">{Object.entries(skills).map(([title,items])=><article key={title}><span className="plus">＋</span><h3>{title}</h3>{items.map(i=><p key={i}>{i}</p>)}</article>)}</div></section>
   <section className="section" id="projects"><p className="label">04 / SELECTED WORK</p><h2>From messy input to a clear answer.</h2><article className="project"><div className="visual"><div className="dash-title">CAPSTONE / ANALYSIS</div><div className="dash"><div><strong>82<span>%</span></strong><small>QUALITY SCORE</small></div><div className="wave">⌁</div><div className="bartext">▂ ▅ ▃ ▇ ▆</div></div></div><div className="project-copy"><p className="company">CASE STUDY 01 · END-TO-END ANALYTICS</p><h3>Data Analyst Capstone Project</h3><p>A simulated real-world reporting workflow that turns raw, messy data into decision-ready insight.</p><dl><div><dt>PROCESS</dt><dd>Cleaned and queried raw data, explored patterns with Python and SQL, then visualized the findings.</dd></div><div><dt>TOOLS</dt><dd>Power BI · Excel · SQL · Python</dd></div><div><dt>OUTCOME</dt><dd>An interactive dashboard presenting key business insights in a stakeholder-friendly format.</dd></div></dl><span className="soon">Repository & live dashboard coming soon</span></div></article></section>
   <section className="section credentials"><div><p className="label">05 / EDUCATION</p><div className="credential"><time>2022—2024</time><h3>M.C.A.</h3><p>Mumbai University · CGPA 7.2</p></div><div className="credential"><time>2019—2022</time><h3>B.Sc. Computer Science</h3><p>Mumbai University · CGPA 9.2</p></div></div><div><p className="label">CERTIFICATION</p><div className="certificate"><b>G</b><div><h3>Google Data Analytics</h3><p>Professional Certificate · Coursera</p></div></div></div></section>
   <section className="contact section" id="contact"><p className="label">06 / CONTACT</p><h2>Have a question hiding<br/>in your data?</h2><p>Let’s turn it into an answer.</p><a className="email" href="mailto:mak.prajesh@gmail.com">mak.prajesh@gmail.com ↗</a><div className="social"><a href="https://linkedin.com/in/prajeshmak" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="https://github.com/prajeshmak" target="_blank" rel="noreferrer">GitHub ↗</a></div></section>
  </main><footer><span>© 2026 Prajesh Makootan</span><span>Designed with clarity. Built with intent.</span><a href="#top">Back to top ↑</a></footer>
 </>
}
